### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by niko0807** [gbbiotwesouth/noderededgemodule#6]
I am trying to run the noderededgemodule in Azure Edge running on Raspberry Pi 4.

I'm using the ARM32 container, but get the following error:

`pi@raspberrypi:~ $ iotedge logs nodered`

`fs.js:114
   throw err;
   ^`
`Error: EACCES: permission denied, copyfile '/usr/local/lib/node_modules/node-red/settings.js' -> '/node-red/settings.js
    at Object.copyFileSync (fs.js:1728:3)
    at copyFile (/usr/local/lib/node_modules/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:68:8)
    at onFile (/usr/local/lib/node_modules/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:25)
    at getStats (/usr/local/lib/node_modules/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/usr/local/lib/node_modules/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/usr/local/lib/node_modules/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/usr/local/lib/node_modules/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-red/red.js:108:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
fs.js:114
    throw err;
    ^`

**Comment by iotblackbelt** [comment]
This issue usually happens when you haven't given de IoT Edge runtime access to the local folder.
In step "_8. On the IoT Edge device create a '/node-red' directory. This directory will hold the changes made to the node-red settings and custom flows created._" Also do a chmod of the directory to 777 or give the iotedge runtime user access to the directory. That will probably fix the problem.

**Comment by iotblackbelt** [comment]
No further action required.

**Comment by micuentadecasa** [comment]
Hi all,
I was able to use your step 8 when working in an IOT Edge simulator in my laptop, the challenge now is to use it on an ASE Device that is totally secured, so I can not access it through shell to create the folder and give permissions to it, how I can solve this issue?
Regards.
